### ISSUE TITLE
@required trait not supported on input and output types of an operation

### ISSUE THREAD

**Issue by aashokgithub** [smithy-lang/smithy-python#182]
Lets assume that we have an operation as shown below 

```smithy
@http(code: 200, method: "POST", uri: "/test_operation")
operation TestOperation {
    input := {
        @required
        test1: String
        @required
        test2: String
    }
    output := {
       @required
       test3: String
    }
}
```

The TestOperationInput and TestOperationOutput that are generated will generate filed which are Optional[String] even if they are annotated with @required

This happens only with input and output of a operation

**Comment by JordonPhillips** [comment]
That's because inputs and outputs with the `@input` / `@output` traits treat top-level members as optional. See [here](https://smithy.io/2.0/spec/aggregate-types.html#structure-optionality) for more information on that. Using the inline input and output shape definition syntax automatically applies those traits.
